#!/bin/bash
echo "Build hello.v"
rm -f v
../goal -o hello src/hello.v
./hello
rm -r hello
echo "Build hello.v"
../goal -o hello.c src/hello.v
gcc -std=c99 -w -o hello hello.c -lm -lpthread
rm -f hello.c
./hello
rm -f hello
echo "Test hello"
../goal -o hello_test src/hello_test.v
./hello_test
rm -f hello_test
